# fly.toml app configuration file generated for instantdb-live-backend-node on 2024-12-26T09:11:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'instantdb-live-backend-node'
primary_region = 'iad'

[build]

[env]
  INSTANT_APP_ID = '016bc8f1-32ca-4af2-9114-a3086b79bc24'

[[services]]

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
